Add SBOM parser and upload endpoint (Milestone 9)
z-arnott/Vega pull request #10
Opened 2023-01-06 23:32 UTC by z-arnott

This PR should be reviewed after PR #9 
**Features:**
All features added to support the sbom upload endpoint
>Add logic to upload endpoint. (Task 9.3)
Files: `src/index.ts` `package.json` 

>Add sbom parser. (Task 9.4)
Formats supported: spdx json, spdx tag/value, cyclonedx json, cyclonedx xml
Files: `src/services/parserContext.services.ts`  `tsconfig.json` 

>Add version support to Package objects
Files: `src/utils/types.utils.ts`

**Tests (Task 9.5):**
Note: unit testing and rudimentary endpoint testing provided, I'm opening an issue to write a more robust test suite for the endpoint.
>endpoint santiy tests 
Files:  `/test/sanity/SanityTests.postman_collection.json`

>parser unit tests
Files:  `/test/unit/SanityTests.postman_collection.json`

**Extra:**
All files in /test/sbom_examples can be ignored, they are auto generated and sample sboms.

2023-01-10 00:08 UTC, Seneli requested changes
Just finished the review and it looks like the implementation concept is solid! I had a few suggestions I flagged as comments so feel free to check them out. All are pretty minor. I also had some questions but mostly out of curiosity. 

Also we should run `npm run prettier` before pushing next time. It'll save a lot of the minor changes between all versions of our files 

Overall, great job!

2023-01-10 00:08 UTC, Seneli commented on src/index.ts
> +let num = SbomFormat.CYCLONEDX_JSON;
unused variable - can delete ?

2023-01-10 00:08 UTC, Seneli commented on src/index.ts
> +import { Package, SbomFormat } from '../src/utils/types.utils';
doesn't look like these 2 are used either - can delete?

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +import {XMLParser, XMLBuilder} from 'fast-xml-parser';
`XMLBuilder` never referenced after import

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +function parse(sbom: any, strategy: SbomFormat): Package[] {
This is an optional convention, but I was taught to structure code so that it starts from the highest level function down to the lowest level. That way the code reads like a newspaper, providing context before any implementation details.

For that reason, I think we should move the `parsingStrategies` dict and `parse` function to the top, under the definition of parser instances.

If TS doesn't let us do that because the parser functions are defined after reference we can forget abt it tho :)

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +spdxJsonParser = function (sbom): Package[] {
I think we should start now with documenting our code via JSDocs. This [link](https://www.section.io/engineering-education/jsdoc-documentation/ ) lays out a template we can follow.

I think documenting the functions for now is fine. The Parser instances + parsing strategies are self explanatory but if you wanna take the extra 5 min it might be worth just writing a line or 2 about it.

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +spdxJsonParser = function (sbom): Package[] {
we can set up the script to generate HTML from jsdocs in a later PR, but i think it would be better to do soon as well. The site i linked shows us how but I've never tried it myself lol

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +spdxJsonParser = function (sbom): Package[] {
We should start documenting our code with JSdoc now so it doesn't creep up on us. Here's a link for how we can get started: [link](https://www.section.io/engineering-education/jsdoc-documentation/). 

Setting up the scripts for it can be done in a later PR but I think documenting the functions is a good practice for now. I don't think you need to document parser instances or `parsingStrategies` because its self explanatory but I'll leave it up to you.

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +function parse(sbom: any, strategy: SbomFormat): Package[] {
I was taught to write code that starts from high level to low level implementation. That way the reader can get an idea of whats in the file at the start and then as they scroll down get the implementation details called by that higher level function.

For that reason I think we should move `parsingStrategies` and `parser` to under the "parser instances" definition.

If typescript doesn't like us referencing a function before it's defined though and starts throwing errors we can leave it though :)

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +        //break if both are defined?
these breaks might be something to discuss with Randa too. IMO we should break if we get EITHER CPE or PURL. No point getting both if its describing the same resource right?

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +      packages.push(p);
very clean! I like how this function is written!

2023-01-10 00:08 UTC, Seneli commented on src/services/parserContext.services.ts
> +      packages.push(p);
this looks like it must have been a pain to do tho. lots of cases for how it can show up :")

2023-01-10 00:08 UTC, Seneli commented on test/unit/parserContext.test.ts
> +let packages: Package []= [{
NICE!

2023-01-10 17:48 UTC, z-arnott commented on src/services/parserContext.services.ts
> +        //break if both are defined?
@rhass-uta can you weigh in?

2023-01-10 17:49 UTC, z-arnott commented on src/services/parserContext.services.ts
> +spdxJsonParser = function (sbom): Package[] {
Is JSDocs set up with the project yet?

2023-01-10 17:49 UTC, z-arnott commented on src/services/parserContext.services.ts
> +function parse(sbom: any, strategy: SbomFormat): Package[] {
Interesting! I've never heard that before but it makes sense
I was worried about Typescript having issues with that like python, but I'll change it and see if it compiles

2023-01-13 02:36 UTC, z-arnott commented on src/services/parserContext.services.ts
> +function parse(sbom: any, strategy: SbomFormat): Package[] {
Typescript compiles this fine. and I agree this convention is easier to follow.
updated!

2023-01-13 02:40 UTC, z-arnott commented on src/services/parserContext.services.ts
> +        //break if both are defined?
spoke with @rhass-uta in person. Consensus is to break at either cpe or purl, and not loop until both are found

2023-01-13 02:42 UTC, z-arnott commented on src/services/parserContext.services.ts
> +      packages.push(p);
thank you! Tag/value format was a literal nightmare :'')

2023-01-15 09:36 UTC, Seneli commented on src/services/parserContext.services.ts
> +spdxJsonParser = function (sbom): Package[] {
no its not but I figure we can do the set up stuff later

2023-01-15 09:39 UTC, Seneli approved these changes

2023-01-15 09:40 UTC, Seneli commented
Nicely done :) We can merge anytime. I think you're right to add docs in a subsequent PR

2023-01-15 13:38 UTC, merged